def github(name, version, options = nil)
  options ||= {}
  options[:repo] ||= "boxen/puppet-#{name}"
  mod name, version, :github_tarball => options[:repo]
end

github 'homebrew', '1.1.0'
github 'boxen', '2.0.0'
github 'stdlib', '3.0.0', :repo => "puppetlabs/puppetlabs-stdlib"
